kind: Namespace
apiVersion: v1
metadata:
  name: nginx-test
  labels:
    name: nginx-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nginx-deployment"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: nginx-test
  labels:
    app: nginx-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-statefulset
  template:
    metadata:
      labels:
        app: nginx-statefulset
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nginx-statefulset"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
